api/location.ts, api/ring-types.ts, homebridge/README.md, homebridge/fan.ts, homebridge/ring-platform.ts
Fan control switches, such as the [GE 14287](https://byjasco.com/products/ge-z-wave-plus-wall-smart-fan-control), can be added to the Ring Alarm Base Station via “Devices > Set Up a Device > Security Devices > Works With Ring”.
Once the device is added, the Ring app prompts you to select a category (options are “Fans”, “Lights” and “Outlets”) (screenshot below):
Homebridge supports a [`Fan` Service](https://github.com/KhaosT/HAP-NodeJS/blob/c11776dc4a145381228ecfadb47dd583977e367d/lib/gen/HomeKitTypes.js#L2881-L2899). This PR enables the `homebridge-ring` plugin to identify fan control devices as Fans to HomeKit.
Without this PR, the plugin identifies these devices as dimmable lights. This is because Ring reuses the `switch.multilevel` `deviceType` for both fans and (multi-level) …
=> Add support for fans

api/ring-camera.ts, api/ring-types.ts, homebridge/README.md, homebridge/camera.ts, homebridge/config.schema.json, homebridge/config.ts
Toggles the “Ring my in-home doorbell” setting (screenshot below):
`python-ring-doorbell` implements this method in [`doorbot.py#L113-L133`](https://github.com/tchellomello/python-ring-doorbell/blob/6d2368b6615368a8724502d59755d14e0aa6e6f9/ring_doorbell/doorbot.py#L113-L133)
I published [`homebridge-ring-smockle@5.8.8`](https://www.npmjs.com/package/homebridge-ring-smockle) to help with testing.
Note: If you toggle the switch in the Home app, then check status in the Ring app, you may see an outdated status, unless you’ve navigated to the main camera settings page.
- Mute doorbell at night
- Mute doorbell when Do Not Disturb is enabled
- Mute doorbell when nursery white noise machine is turned on
=> Enable or disable in-home doorbell (via API or Homebridge Switch)

README.md, homebridge/README.md
1. Switch both PayPal Donate badges to badgen.net for consistency
2. Add MIT license badge to main README
3. Add homebridge:veriied badge (to /homebridge/ README)
=> README badge cleanup

api/api.ts, api/location.ts, api/ring-chime.ts, api/ring-types.ts, examples/chime-example.ts
Firstly, thank you for this awesome repo @dgreif. Definitely one of the highest quality homebridge repos to date!
Hoping I can contribute here a bit for issue https://github.com/dgreif/ring/issues/262. I haven't yet worked with a speaker device type like you had mentioned in that issue, so I figured I would try to implement the Chime API side of things and then discuss the homebridge side a bit further with you.
Currently with this PR, a chime has these abilities:
- Play a motion sound
- Play a ding sound
- Set a snooze interval
- Clear a snooze interval
- Fetch available ringtones
- Update chime with new volume/ringtones
I added an example of setting a new ringtone, then the `playSound` for both dings and motion events.
It would be awesome to have the ability to trigger `playSound` by …
=> Ring Chime support

api/ring-camera.ts
Addresses issue #281 - if you call streamVideo from an onNewDing handler then the call to getSipOptions can't find the new ding in the activeDings so ends up invoking a new VOD, which in turn creates a new ding and calls processActiveDing. By swapping the order of these next() calls, a client can listen to either event and start a stream in the observer without causing the spurious VOD ding to be created.
=> Prevent ding-loop when streaming from onNewDing

api/ring-types.ts, homebridge/ring-platform.ts
Adds support for the Tilt Sensor that can be purchased in the ring shop:
https://shop.ring.com/products/ecolink-tilt-sensor-zwave2-5-eco
Will display as a Contact Sensor by default in the Home app, but can be switched via the 'Display As' to Garage Door and it works as expected then.
=> feat(homebridge): support tilt sensor

api/ring-camera.ts, homebridge/README.md, homebridge/camera.ts, homebridge/config.schema.json, homebridge/config.ts
Added config option to let a standard (non-doorbell) camera create a doorbell accessory that simulates a doorbell press when they detect motion. Defaults off.
AppleTV notifications only support doorbell accessories right now, so this lets you to make any camera automatically open a live picture-in-picture thumbnail video on-screen when it detects motion. You can turn individual camera alerts on/off on a device in homekit settings.
The existing onMotionDetected seems to need to generate a motion alert whenever homebridge is restarted which made it annoying and wasn't very reliable for doorbell-style triggers - but adding an onMotionStart that worked similar to onDoorbellPressed seems to work really well, but theres probably a much better way of doing that I'm missing though?
=> Allow cameras to trigger apple tv video notifications when motion is detected

homebridge/README.md
The link to ffmpeg-for-homebridge's github page was broken. This commit fixes it.
=> Fix a typo in the link to ffmpeg-for-homebridge

api/sip-session.ts
ffmpeg spends about 3 seconds analyzing the RTP stream to determine the details of the streamed video. This change instructs the RTP decoder to use a fixed frame size, and ffmpeg to spend nearly no time analyzing the incoming stream. If the native frame size of the camera doesn't match this then it has no adverse effects that I can observe. I find this allows streaming to start in less than 1 second.
cc @dgreif
=> Enable faster start of stream

homebridge/outlet.ts, homebridge/ring-platform.ts
I recently installed a [GE/Jasco Z-Wave In-Wall Tamper-Resistant Smart Outlet (14288)](https://byjasco.com/products/ge-z-wave-plus-wall-tamper-resistant-smart-outlet). It is currently identified as a [Switch](https://developers.homebridge.io/#/service/Switch), but Homebridge supports a distinct [Outlet](https://developers.homebridge.io/#/service/Outlet) Service.
Here is the relevant output from `npm run device-data-cli` (specifically, note [`"deviceType": "switch"`](https://github.com/dgreif/ring/blob/d436ca263b3bc556768fc894d3cda3578fc90881/api/ring-types.ts#L25) and [`"categoryId": 1`](https://github.com/dgreif/ring/blob/d436ca263b3bc556768fc894d3cda3578fc90881/api/ring-types.ts#L38)):
```json
{
"adapterType": "zwave",
"batteryStatus": "none",
"categoryId": 1,
"commStatus": "ok", …
```
=> Add support for outlets

api/rest-client.ts
Similar to `ENOTFOUND`, `EREFUSED`, and `ENETUNREACH`, flush the DNS cache after an `EHOSTUNREACH` error. This prevents the unrecoverable (until Homebridge is restarted) state I described [on Discord](https://discord.com/channels/432663330281226270/432671438156070931/794375306235346994).
@dgreif [pointed out](https://discord.com/channels/432663330281226270/432671438156070931/795295041211465728) this is similar to #374, and suggested the fix implemented in this PR:
> [I]t might have something to do with the network interface not being initialized yet if your daemon starts too early in the boot process.  Then DNS caching could possibly cache the wrong info and stay permanently broken.  I've put in workarounds for a number of these issues, but not EHOSTUNREACH specifically.  See …
=> Flush DNS cache after `EHOSTUNREACH`

api/ring-camera.ts, homebridge/camera.ts
This adds support for showing whether battery powered doorbells are hardwired by using the charging status. I tested this by disconnecting my doorbells from the wiring, and it works as expected there.
I only have access to two different models of battery doorbell, but I don't see any reason why this should cause issues with any other device types.
=> Show charging status for battery doorbells

api/api.ts, api/rest-client.ts
Fixes #850 by clearing timeouts set to refresh auth token when RingApi.disconnect() is called.
=> clear timeouts when RingApi.disconnect() is called

api/api.ts, api/location.ts, api/rest-client.ts, api/ring-camera.ts, api/ring-chime.ts, api/ring-device.ts, api/ring-types.ts, api/sip-session.ts, api/util.ts
The primary issue is that constructor assignment members are being used by
member variable initializers. Member variables are initialized before constructor members
causing a host of null reference problems. You can view these errors
by changing compilerOptions.target to esnext.
=> Updates to fix modern compilerOptions targets.

api/rest-client.ts
I need a way to be able to create requests with the ring api, with no retries. the current rest client will always retry on no response, which happens on snapshots. I need to manage snapshot recovery myself, and that involves knowing when the request fails, and without any retries at all.
=> allow option to disable retry mechanism on no response

packages/ring-client-api/api.ts
Hi @dgreif,
While adding support for intercoms to ring-mqtt I had one user that had really strange behavior in that his device would go offline after a few minutes.  To determine if a device without a websocket is online/offline I use a simple heartbeat function which relies on the fact that onData function for polled devices is called every 20 seconds.  For this user, this polling never happened, and even if I manually called requestUpdate() I would just get no response.  However, when I ran the same code on my account, it worked.
The only real difference between my account and the users account is that I also have cameras and chimes, while this user only had an intercom and, after some digging, it looks like this is caused by the check in listenForDeviceUpdates() which returns prior to …
=> Fix polling when only intercoms exist

packages/ring-client-api/streaming/peer-connection.ts
Hi @dgreif ,
For months I've been plagued by random artificing when viewing streams with ring-client-api and I finally had time to dig into it.  For a while I thought this was some problem with werift itself, perhaps just poor performance overall, but after adding some debugging it was clear that, for my case UDP packets were occassionally lost before they reached even my firewall.
What didn't make sense was that videos viewed with the Ring app or Ring web dashboard on the same device/network never experienced this issue so I took some packet traces and really started digging into it and finally I noticed that both the Ring web dahsboard and app use RTX to support retransmission of lost packets.  You can see the same occassional packet loss in the streams viewing in Google browser, but …
=> Enable retransmission of lost RTP packets via RTX

.changeset/real-onions-tickle.md, package-lock.json, packages/ring-client-api/api.ts, packages/ring-client-api/package.json, packages/ring-client-api/ring-camera.ts, packages/ring-client-api/ring-types.ts
Since the switch to push notifications, the dingId has been parsed as a number, which loses the last three digits of precision. This makes it impossible to use that dingId to look up dings in the ring history.
This change switches to parsing the ding payload with `json-bigint` and the ding ID field is now a string to store the id to its complete precision.
=> Support complete dingId

.changeset/tame-onions-trade.md, package-lock.json, packages/homebridge-ring/camera-source.ts, packages/homebridge-ring/package.json
These changes are pretty minor.  Based on what I could determine, the audio from the doorbell was single channel, 24Khz sample rate, and a 24Kb bitrate, so this uses the same for the return audio.  Also, disabled Opus variable bit rate, this seems to reduce the stuttering and overall robot sounding voice as well as works around the issues with recent werift versions.
The audio quality is still not as good as that from the Ring app, I'm not sure if this is due to Homekit audio, the transcoding itself (although I tried a lot of different options and this seemed to be the best), or if Ring is doing some type of audio filtering.  The audio from Ring seems lower pitched, like they are filtering it through an equalizer or lowpass filter, which perhaps they are because the speakers in these …
=> Tweak ffmpeg Opus encoding optoins for more reliable audio

.changeset/poor-moles-cry.md, packages/homebridge-ring/camera-source.ts, packages/homebridge-ring/opus-repacketizer.ts
Super small fix here.  I appears the tweaks to Opus encoding which disabled variable bitrate encoding caused ffmpeg to produce RTP packets which slight exceed the current maximum configured packet size of 188 (176 data bytes).
This size works over local networks because Homekit requests a packet time (frame size) of 20ms which produces packets of ~60-80 bytes.  However, over LTE/5G network Homekit requests packet time of 60ms, which produces packets of 3x that size, or 180-240 bytes, which is over the hardcoded 188 byte size.  This causes ffmpeg to exit unexpectedly due to RTP packet size too big error and thus streaming will not work over LTE/5G networks (I'm not convinced this is not a bug with ffmpeg, as I would have expected the packet to be fragmented, but I don't really understand …
=> Fix ffmpeg error when streaming over LTE/5G

package-lock.json, packages/ring-client-api/package.json, packages/ring-client-api/streaming/streaming-session.ts
Integrating in https://github.com/homebridge/camera-utils/pull/584
Would appreciate if we could do a new release once this is merged so I can use in my application.
=> ffmpeg: Expose stdout callback to user

.changeset/mighty-steaks-itch.md, packages/ring-client-api/rest-client.ts
This PR addresses the recently introduced API changes which appears to have disabled the legacy app.ring.com URL which prevents tickets for socket connections from being acquired.  This patch updates the URL with the one used by current versions of the Ring android app which seems to effectively work around the issue.
=> Update appApi  endpoint

packages/homebridge-ring/base-accessory.ts, packages/homebridge-ring/base-device-accessory.ts, packages/homebridge-ring/camera.ts, packages/homebridge-ring/intercom.ts
This updated or removes old depreciated code that has now been removed from HAP-NodeJS v1.0.0 which will be included in a future version of Homebridge.
Until this is resolved Users that try to use the current Homebridge beta, they will get the following error:
```
[7/10/2024, 9:27:49 PM] [Ring] Error connecting to API
[7/10/2024, 9:27:49 PM] [Ring] TypeError: Cannot read properties of undefined (reading 'UUID')
at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:522:37)
at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
at Beam.getService (/usr/local/lib/node_modules/homebridge-ring/lib/base-accessory.js:29:28)
at Beam.registerCharacteristic …
```
=> Fixes for HAP-NodeJS v1.0.0

packages/ring-client-api/ring-camera.ts, packages/ring-client-api/ring-types.ts
The current logic checks only the primary battery even each camera has a secondary battery.
This PR fixes this issue by checking the secondary battery in getBatteryLevel method.
Related issue: #1312
=> Fix batteryLevel to check secondary battery

packages/ring-client-api/api.ts
This fix stops the code from pushing the old FCM token to Ring when a new token is generated during registration, for example, due to migration to FCMv1 APIs for registration.  The bug happens because the very last command in the push notification initialization sequence currently sends the FCM token to Ring any time  `credentials` is defined:
```
if (credentials) {
onPushNotificationToken.next(credentials.fcm.token)
}
```
The problem with this is `credentials` is assigned prior to registration so it would still hold the old FCM token even if a new token was generated during the registration process.  Because of this, the sequence of events was something like this:
1) credentials = config.pnc (assuming credentials already existed)
2) Push notification would register using existing …
=> Don't send old FCM tokens when new token is generated during startup

.changeset/purple-teachers-applaud.md, package-lock.json, packages/ring-client-api/package.json, packages/ring-client-api/rest-client.ts
Hi @dgreif,
This PR is an attempt to address the native fetch/undici issues that were causing http requests to stop.  I can provide a hugely detailed analysis of the failure, but, suffice it to say, I believe it has to do with how undici uses keepalive and pool connections.  There are quite a number of similar issues on the undici project page.
To work around this, the PR imports Agent from the undici package and creates a custom dispatcher with fewer max TCP connections and much longer keepalive.  This makes native NodeJS fetch behave more like browser fetch implementations as well as other http client libs like got (the actual values used are the same as Firefox).  This actually has a mostly positive impact for all users as it dramatically reduces the number of DNS lookups and TCP …
=> Tune fetch for improved connection management

.changeset/shy-needles-stare.md, packages/ring-client-api/api.ts
This patch addresses an unhandled promise rejection that occurs in push-receiver 4.3.0.  This version of push-receiver introduced a new whenReady promise that consumers can use to know when the initial connection is ready.  However, it seems to have a bug when the socket connection fails as the code rejects the promise but has no catch for this rejection, thus creating an unhandled promise which leads to a process crash on modern NodeJS >15 which exit on unhandled promises by default.
It's possible to attach a catch handler outside of the library during first use, but the issue is that a new promise is created on every connection attempt, so, while that will catch the initial failure, subsequent retries are new promises without a catch.
This patch takes a different approach, instead of …
=> Catch to prevent push-receiver crash on disconnect

packages/ring-client-api/ring-types.ts
I recently purchased the Pro version of the Battery Video Doorbell - I am trying to get the actual device model to show up on the addons I use, Scrypted, Home Assistant (etc.) it makes the device look better rather it saying unknown model in Homekit 😋 
I presume just the v3 visual identifier needs to be added in the types - functionality is working 👍🏻
=> Add support for Battery Video Doorbell Pro

packages/ring-client-api/ring-types.ts
Add support for new Kidde Smart Smoke and CO detector (https://ring.com/carbon-monoxide-smoke-detector-kidde)
Device type was discovered by listing devices in account and using the `deviceType`.
=> Add KiddeSmokeCoAlarm to RingDeviceType
